version: '3.9'
name: hackgpt
services:
  streamlit:
    image: python:3.9-slim
    ports:
      - '8501:8501'
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run app.py"
    restart: unless-stopped